### ISSUE TITLE
Can't start server for demo

### ISSUE THREAD

**Issue by mcpierce** [serhiisol/ngx-auth-example#4]
The instructions say to execute the following line:

```
npm run server
```

But when I do this I get the following:

```
mcpierce@Darryls-MacBook-Pro ~/temp/ngx-auth-example (master) $ npm run server
npm ERR! missing script: server

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mcpierce/.npm/_logs/2018-07-28T16_22_15_710Z-debug.log
```

**Comment by serhiisol** [comment]
ah. sorry, documentation is incorrect. you have to open server folder, install there all the dependencies and then do `npm start` (which will compile server and start it). Readme has been updated.
